"""init transactions

Revision ID: e7c4ee576a24
Revises: 5104f9b3dbf9
Create Date: 2026-04-01 16:40:37.734712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7c4ee576a24'
down_revision: Union[str, Sequence[str], None] = '5104f9b3dbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('spent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_transactions_user_created_at'), table_name='transactions')
    op.create_index(op.f('ix_transactions_spent_at'), 'transactions', ['spent_at'], unique=False)
    op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transactions', 'note')
    op.drop_column('transactions', 'date')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('transactions', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_transactions_spent_at'), table_name='transactions')
    op.create_index(op.f('ix_transactions_user_created_at'), 'transactions', ['user_id', 'created_at'], unique=False)
    op.drop_column('transactions', 'spent_at')
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###
